//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathConfigSource) DeepCopyInto(out *PathConfigSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathConfigSource.
func (in *PathConfigSource) DeepCopy() *PathConfigSource {
	if in == nil {
		return nil
	}
	out := new(PathConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfigSource) DeepCopyInto(out *ServerConfigSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfigSource.
func (in *ServerConfigSource) DeepCopy() *ServerConfigSource {
	if in == nil {
		return nil
	}
	out := new(ServerConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsBackend) DeepCopyInto(out *XdsBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsBackend.
func (in *XdsBackend) DeepCopy() *XdsBackend {
	if in == nil {
		return nil
	}
	out := new(XdsBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XdsBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsBackendSpec) DeepCopyInto(out *XdsBackendSpec) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(ServerConfigSource)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(PathConfigSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsBackendSpec.
func (in *XdsBackendSpec) DeepCopy() *XdsBackendSpec {
	if in == nil {
		return nil
	}
	out := new(XdsBackendSpec)
	in.DeepCopyInto(out)
	return out
}
