//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathConfigSource) DeepCopyInto(out *PathConfigSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathConfigSource.
func (in *PathConfigSource) DeepCopy() *PathConfigSource {
	if in == nil {
		return nil
	}
	out := new(PathConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfigSource) DeepCopyInto(out *ServerConfigSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfigSource.
func (in *ServerConfigSource) DeepCopy() *ServerConfigSource {
	if in == nil {
		return nil
	}
	out := new(ServerConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TlsSettings) DeepCopyInto(out *TlsSettings) {
	*out = *in
	if in.CaCertificates != nil {
		in, out := &in.CaCertificates, &out.CaCertificates
		*out = new(XdsConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(v1.Hostname)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TlsSettings.
func (in *TlsSettings) DeepCopy() *TlsSettings {
	if in == nil {
		return nil
	}
	out := new(TlsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsBackend) DeepCopyInto(out *XdsBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsBackend.
func (in *XdsBackend) DeepCopy() *XdsBackend {
	if in == nil {
		return nil
	}
	out := new(XdsBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XdsBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsBackendSpec) DeepCopyInto(out *XdsBackendSpec) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(XdsConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Tls != nil {
		in, out := &in.Tls, &out.Tls
		*out = new(TlsSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsBackendSpec.
func (in *XdsBackendSpec) DeepCopy() *XdsBackendSpec {
	if in == nil {
		return nil
	}
	out := new(XdsBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XdsConfigSource) DeepCopyInto(out *XdsConfigSource) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(ServerConfigSource)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(PathConfigSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XdsConfigSource.
func (in *XdsConfigSource) DeepCopy() *XdsConfigSource {
	if in == nil {
		return nil
	}
	out := new(XdsConfigSource)
	in.DeepCopyInto(out)
	return out
}
